"""remove image table

Revision ID: bad8740f77b7
Revises: b21278996d7f
Create Date: 2024-05-20 17:46:16.497682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bad8740f77b7'
down_revision: Union[str, None] = 'b21278996d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.add_column('chargers', sa.Column('image_filename', sa.String(length=255), nullable=True))
    op.drop_column('chargers', 'img')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chargers', sa.Column('img', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('chargers', 'image_filename')
    op.create_table('image',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_type', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('content', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
